server:
  port: 8080

spring:
  session:
    jdbc:
      initialize-schema: always
  flyway:
    enabled: true
    schemas: tasks-bot
    baseline-on-migrate: true
    locations: classpath:db.migration
  datasource:
    schemas: tasks-bot
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
  mode: LONG_POLLING

logging:
  level:
    ROOT: ${LOG_LEVEL}
  file:
    name: 'bot.log'
