bot:
  token: # todo set your
  username: # todo set your

mail:
  host: # todo set your
  port: # todo set your
  username: # todo set your
  password: # todo set your

server:
  port: 8083

spring:
  main:
    allow-bean-definition-overriding: true
  jmx:
    enabled: false
  cache:
    type: NONE
  datasource:
    url: jdbc:postgresql://localhost:5555/db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ROOT: INFO
management:
  server:
    port: 8083