server:
  port: 8083

grpc:
  port: 9090

spring:
  mail:
    properties:
      "mail.smtp.ssl.enable": true
  session:
    jdbc:
      initialize-schema: always
  flyway:
    enabled: true
    schemas: tasks-bot
    baseline-on-migrate: true
    locations: classpath:db.migration
  datasource:
    schemas: tasks-bot
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

bot:
  token: ${BOT_TOKEN}
  username: ${BOT_USERNAME}
  mode: LONG_POLLING

mail:
  host: ${MAIL_SERVER_HOST}
  port: ${MAIL_SERVER_PORT}
  username: ${MAIL_USER}
  password: ${MAIL_PASS}
  content:
    bot-name: "Bot tasks"
    subject: "received new message"

logging:
  level:
    ROOT: ${LOG_LEVEL:INFO}
  file:
    name: 'logs/bot.log'
