bot:
  token: 'need override'
  username: 'need override'

spring:
  cache:
    type: NONE
  datasource:
    url: jdbc:postgresql://localhost:5555/db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ROOT: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE